### ISSUE TITLE
Howto: ocis on Ubuntu with docker compose

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/docs-ocis#774]
# Description

## User Stories

* > As a user who wants to be independent of big tech SaaS, I want to evaluate a local installation of ocis  so that I know if I can handle self-hosting in the future.

## Value

- increase adoption rate in community

## Acceptance Criteria

- [ ] write a how-to guide how to install ocis
- [ ]   OS: Ubuntu LTS
  - [ ]   instance is only accessible via local network/hostname (192.168.0.58:9200 / localhost)
  - [ ]   Environment: docker compose
  - [ ]   Storage: Decomposed fs on local posix
  - [ ]   IDM: out-of-the-box "Libre IDM"
  - [ ]   same apps as on: https://ocis.ocis-wopi.latest.owncloud.works/
- [ ] user can login via eg. localhost:9200 in browser

**Comment by tbsbdr** [comment]
https://doc.staging.owncloud.com/ocis/next/depl-examples/ubuntu-compose/ubuntu-compose-basic.html

**Comment by tbsbdr** [comment]
@mmattel
https://doc.staging.owncloud.com/ocis/next/depl-examples/ubuntu-compose/ubuntu-compose-test.html is quite a bunch of text. If this is the quickest test setup for an evaluation we should not publish it, as I consider it too laborious. I hope we can reuse parts of the text in other doc texts.

### What else can we provide for a quick evaluation?
If there is no quick way of evaluating the wopi example, we could think of providing just the command to get https://hub.docker.com/r/owncloud/ocis running so that the user gets at leas a quick experience of success. Let's talk about alternatives in out weekly @mmattel

**Comment by mmattel** [comment]
We already have that, see: [Minimal Bare Metal](https://doc.owncloud.com/ocis/next/depl-examples/minimal-bare-metal.html).

I hope that you see that work as part of a bigger scope...

**Comment by tbsbdr** [comment]
- if possible, reuse the whole text within/for a guide, but lets not state it as "Test" or "Evaluation" because its way too long for a testing usecase

**Comment by tbsbdr** [comment]
@mmattel please see my [comment above](https://github.com/owncloud/docs-ocis/issues/774#issuecomment-2147612313) regarding https://doc.staging.owncloud.com/ocis/next/depl-examples/ubuntu-compose/ubuntu-compose-eval.html

--> I dont want such a long text for evaluation or testing purposes. the tldr you did is way better for a quick evaluation and provides a good erfolgserlebnis ("_up and running as fast as possible_"). I suggest, if there are pieces of the text which you need in other guides, please cut/paste them ("reuse") if useful/suitable. But the text as is should not be published as it does not create the user value of a "quick evaluation". if its not possible to do a quick evaluation and provide a erfolgserlebnis for ocis+wopi, we can not write a text about it.

**Comment by mmattel** [comment]
Ok, hmmm?
I have an opposite opinion and we need to discuss via online meeting...

**Comment by tbsbdr** [comment]
lets please discuss here async

**Comment by mmattel** [comment]
1. Definition of the target audiences knowledge stack:
   * Based on the definition and the order made, the document takes care about the steps necessary.
   * Naturally, if the required knowledge stack raises, the steps needed for a sufficient guide become less.
     Saying this, we must not write such guides for devs but for a potential interrested community...)
2. Deployment example used:
   * The deployment example used is intentionally, because it is not about showing a webUI but what a user group intends to do - and this is sharing and collaborative working on documents.
   * We do not get credits for EFSS but for real life experiences about an environment which includes web office.
3. Document series:
    * One must start with an impression and wants to get eager to use it in production. Therefore we offer different first steps depending where one wants or can start (bare metal, compose etc).
    * The production document running locally using Letsencrypt is the next one in the series of documents.
    * Based on the above, the planned "Hetzner" variant hands over local services to cloud services which also closes up the series.
4. Marketing:
   * To gain community interrest and positive impacts, a series of install documents must be provided. It is absolutely insufficient just using a minimal bare metal and think that the community will be satisfied. Such a thinking is dev oriented and does not match community needs and views.
   * By providing the series with different levels, follow up marketing activities can be set up like articles in magazines or uses in speeches etc that highlight the capabilities one can immediately try based on the readers level. Fewer offers will lead to low and bad responses and counteracts the intention to spread the word.
   * We are in a competitive market and not showing what we are capable is honestly a very bad idea.

**Comment by tbsbdr** [comment]
okay, lets talk 😅

**Comment by mmattel** [comment]
Closing via #884 and #891
